### ISSUE TITLE
Fails to find the function App from time to time

### ISSUE THREAD

**Issue by patelchandni** [microsoft/pipelines-appservice-lib#56]
https://github.com/Azure/functions-action/issues/116

The following app doesn't exist error appears even if the function app is already there and exists for hours.

```
Error: Resource func-my-function doesn't exist.
    at Function.<anonymous> (/home/runner/work/_actions/Azure/functions-action/v1/node_modules/azure-actions-appservice-rest/Utilities/AzureResourceFilterUtility.js:21:23)
    at Generator.next (<anonymous>)
    at fulfilled (/home/runner/work/_actions/Azure/functions-action/v1/node_modules/azure-actions-appservice-rest/Utilities/AzureResourceFilterUtility.js:5:58)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
```

**Comment by akbast** [comment]
any news on this?
